---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ClingTo.
--- DateTime: 2025/5/20 23:47
---

function Test()
    local a = { 'Value1', 'Value2', 1.1 }
    for i in a do
    print(i)
    end
    
end