---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ClingTo.
--- DateTime: 2025/5/20 15:38
---

-- 注意别忘了命名空间
function get_system(system_interface_type)
    local get_system_function = xlua.get_generic_method(CS.Core.QFrameWork.GameContext, "GetSystem")
    local system_function = get_system_function(system_interface_type)

    local system = system_function(CS.Core.QFrameWork.GameContext.Interface)
    return system
end

function get_bullet_system()
    return get_system(CS.GameAbilitySystem.Buff.Manager.IBulletManagerSystem)
end

function get_mouse_position()
    --Input.mousePosition
    local mousePosition = CS.UnityEngine.Input.mousePosition
    
end

function create_common_bullet(timeline)
    --CS.UnityEngine.Debug.Log('create_common_bullet')
    local system = get_bullet_system()
    system:CreateBulletById('Bullet_Common', timeline.Caster)
end
